services:
  db:
    image: postgres
    container_name: checkpoint-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: checkpoint
    ports:
      - "5433:5432"
    volumes:
      - ./checkpoint:/var/lib/postgresql/data